name: medsegpy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.3
  - numpy-base=1.16.3
  - pip=10.0.1=py36_0
  - pyparsing=2.2.0
  - python=3.6.8
  - graphviz
  - pip:
    - configparser==3.5.0
    - cython==0.29
    - fvcore
    - h5py==2.8.0
    - keras==2.1.6
    - matplotlib==3.0.3
    - medpy==0.4.0
    - natsort==5.3.3
    - opencv-python
    - pandas==0.23.4
    - pillow==5.2.0
    - pydot==1.2.4
    - pydotplus==2.0.2
    - scikit-image==0.14.2
    - scipy==1.1.0
    - seaborn==0.9.0
    - simpleitk==1.1.0
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - resnet
