EXP_NAME: "CT Supervised Seg - 10%"
DESCRIPTION: "CT fully supervised segmentation using 10% training data"
LEARNING_TAG: "supervised"
PRIMARY_TASK: "segmentation"
MODEL_NAME: "ContextSegmentation"
TEST_METRICS: ["DSC", "VOE", "CV"]
INITIAL_LEARNING_RATE: 0.001
LR_SCHEDULER_NAME: "StepDecay"
DROP_FACTOR: 0.9
DROP_RATE: 2.0
MIN_LEARNING_RATE: 1e-08
USE_EARLY_STOPPING: True
EARLY_STOPPING_CRITERION: "val_loss"
EARLY_STOPPING_MIN_DELTA: 1e-03
EARLY_STOPPING_PATIENCE: 10
IMG_SIZE: (512, 512, 3)
NORMALIZATION: "GroupNorm"
NORMALIZATION_ARGS: {"groups": 16}
WEIGHT_STANDARDIZATION: True
KERNEL_INITIALIZER: "he_normal"
LOSS: "MULTI_CLASS_DICE_LOSS"
NUM_GRAD_STEPS: 1
N_EPOCHS: 500
NUM_WORKERS: 1
NUM_FILTERS: [[32, 32], [64, 64], [128, 128], [256, 256], [512, 512]]
TAG: "Abdominal_CT_DataLoader"
PRELOAD_DATA: True
CATEGORIES: [1, 2, 3, 4]
TRAIN_BATCH_SIZE: 9
VALID_BATCH_SIZE: 9
TEST_BATCH_SIZE: 9
TRAIN_DATASET: "abCT_seg_10_train"
VAL_DATASET: "abCT_seg_val"
TEST_DATASET: "abCT_seg_test"
SEED: 11725701
OUTPUT_DIR: "css://abct/fully_supervised/10_perc"
