MODEL_NAME: "segnet_2d"
DEPTH: 4
NUM_CONV_LAYERS: [2, 3, 3, 3]
NUM_FILTERS: [32, 128, 256, 512]
USE_BOTTLENECK: True
INITIAL_LEARNING_RATE: 8e-3
LR_SCHEDULER_NAME: "StepDecay"
LR_MIN_DELTA: 2e-4
LR_PATIENCE: 4
DROP_FACTOR: 0.5
DROP_RATE: 3.0
USE_EARLY_STOPPING: True
EARLY_STOPPING_CRITERION: "val_loss"
EARLY_STOPPING_MIN_DELTA: 1e-05
EARLY_STOPPING_PATIENCE: 12
IMG_SIZE: (384, 384, 1)
KERNEL_INITIALIZER: "he_normal"
MIN_LEARNING_RATE: 1e-08
NUM_GRAD_STEPS: 4
N_EPOCHS: 100
TAG: "DefaultDataLoader"
TRAIN_BATCH_SIZE: 10
VALID_BATCH_SIZE: 40
TEST_BATCH_SIZE: 40
TRAIN_DATASET: "oai_2d_train"
VAL_DATASET: "oai_2d_val"
TEST_DATASET: "oai_2d_test"
CATEGORIES: (0, (1, 2), 3, (4, 5))
OUTPUT_DIR: "tcv3://test_exps/segnet_2d/4x_wide"
SEED: 1
NUM_WORKERS: 4
