#!/bin/bash

# List of 3D unet experiments
#
# @usage (from terminal/command line):
# ./unet3d-exps GPU_ID(s)
# eg: "./unet3d-exps 0", "./unet3d-exps 0,1"
#
# @initialization protocol:
#   1. run "chmod +x unet3d-exps" from the command line
#
# @author: Arjun Desai, Stanford University
#          (c) Stanford University, 2019

if [ $# -lt 1 ]; then
	echo "Please provide gpus to run inference on in format `0` for single gpu or `0,1,2` for multiple gpus"
	exit 125
fi

GPU=$1

# Navigate to project directory
cd ../..

ARGS='--tag oai_3d --n_epochs 100 --use_step_decay --drop_factor 0.6 --drop_rate 4 --initial_learning_rate 0.001 --experiment vol --train_batch_size 1 -g '$GPU

# Experiment 0: 2D unet
#python -m oai_train unet_2d $ARGS

# Experiment 1: 3D unet (4 slices)
python -m oai_train unet_3d --img_size '(288,288,4,1)' $ARGS
exit
# Experiment 2: 3D unet (8 slices)
python -m oai_train unet_3d --img_size '(288,288,8,1)' $ARGS

# Experiment 2: 3D unet (16 slices)
python -m oai_train unet_3d --img_size '(288,288,16,1)' $ARGS

# Experiment 2: 3D unet (32 slices)
python -m oai_train unet_3d --img_size '(288,288,32,1)' $ARGS
