MODEL_NAME: "UNet2D"
INITIAL_LEARNING_RATE: 0.001
LR_SCHEDULER_NAME: "StepDecay"
DROP_FACTOR: 0.9
DROP_RATE: 2.0
MIN_LEARNING_RATE: 1e-08
USE_EARLY_STOPPING: True
EARLY_STOPPING_CRITERION: "val_loss"
EARLY_STOPPING_MIN_DELTA: 1e-05
EARLY_STOPPING_PATIENCE: 8
IMG_SIZE: (384, 384, 1)
DEPTH: 6
KERNEL_INITIALIZER: "he_normal"
LOSS: ("dice", "sigmoid")
NUM_GRAD_STEPS: 1
NUM_WORKERS: 4
N_EPOCHS: 100
TAG: "DefaultDataLoader"
CATEGORIES: (0, (1, 2), 3, (4, 5))
TRAIN_BATCH_SIZE: 24
VALID_BATCH_SIZE: 40
TEST_BATCH_SIZE: 80
TRAIN_DATASET: "oai_2d_whitened_train"
VAL_DATASET: "oai_2d_whitened_val"
TEST_DATASET: "oai_2d_whitened_test"
SEED: 11725701
OUTPUT_DIR: tcv3://architecture/unet_2d/oai_whitened_seed-11725701

