[DEFAULT]
cp_save_tag = segnet_2d
initial_learning_rate = 0.001
lr_scheduler_name = StepDecay
drop_factor = 0.7
drop_rate = 3.0
use_early_stopping = True
early_stopping_criterion = val_loss
early_stopping_min_delta = 1e-05
early_stopping_patience = 12
img_size = (384, 384, 1)
kernel_initializer = he_normal
min_learning_rate = 1e-08
num_grad_steps = 4
n_epochs = 100
output_dir = tcv3://hyperparameters/segnet_2d/oai_4x_default
tag = oai_aug
test_batch_size = 80
test_dataset = oai_2d_test
tissues = [0, [1, 2], 3, [4, 5]]
train_batch_size = 8
train_dataset = oai_2d_train
valid_batch_size = 40
val_dataset = oai_2d_val
