INITIAL_LEARNING_RATE: 0.001
LR_SCHEDULER_NAME: "StepDecay"
DROP_FACTOR: 0.9
DROP_RATE: 2.0
USE_EARLY_STOPPING: True
EARLY_STOPPING_CRITERION: "val_loss"
EARLY_STOPPING_PATIENCE: 8
EARLY_STOPPING_MIN_DELTA: 1e-05
IMG_SIZE: (384, 384, 1)
KERNEL_INITIALIZER: "he_normal"
MIN_LEARNING_RATE: 1e-06
N_EPOCHS: 100
OUTPUT_DIR: ""
TAG: "DefaultDataLoader"
TRAIN_BATCH_SIZE: 24
VALID_BATCH_SIZE: 40
TEST_BATCH_SIZE: 80
TRAIN_DATASET: "oai_2d_train"
VAL_DATASET: "oai_2d_val"
TEST_DATASET: "oai_2d_test"
CATEGORIES: (0, (1, 2), 3, (4, 5))
