_BASE_: "../template.yaml"
MODEL_NAME: "FCDenseNet"
DEPTH: 3
NUM_LAYERS: (2,)
NUM_FILTERS: (16,)
NUM_FILTERS_HEAD_CONV: 32
OUTPUT_DIR: "tcv3://test_exps/fc_densenet/basic"
N_EPOCHS: 40
TRAIN_BATCH_SIZE: 1
VALID_BATCH_SIZE: 4
TEST_BATCH_SIZE: 4
NUM_GRAD_STEPS: 24
INITIAL_LEARNING_RATE: 1e-4
LR_SCHEDULER_NAME: ""
NUM_WORKERS: 4